italia/daf-dataportal

- Dockerfile
- public/css/LICENSE
Added docker and license for css core
> Added docker and license for css core

- Dockerfile
- src/components/Header/Header.js
- src/components/IngestionForm/inputform_reader.js
- src/components/IngestionWizard/WizardForm.js
- src/components/IngestionWizard/WizardFormMetadata.js
- src/components/IngestionWizard/WizardFormThirdPage.js
- src/components/IngestionWizard/inputform_reader.js
- src/components/IngestionWizard/validate.js
- src/config/serviceurl.js
- src/helpers/TrasformFormToDcat.js
- src/views/DashboardManager/components/services/WidgetService.js
- src/views/UserStory/components/services/UserStoryService.js
Add services to config, Bug fixing Wizard
> Add services to config, Bug fixing Wizard

- src/components/IngestionWizard/WizardFormMetadata.js
- src/config/serviceurl.js
- src/containers/Full/Full.js
- src/views/DashboardManager/components/services/DashboardService.js
Bug fixed file title and css style white bk and padding 0
> Bug fixed file title and css style white bk and padding 0

- package.json
- src/views/Dashboard/Dashboard.js
- src/views/Dashboard/services/HomeService.js
Timeline in homepage still to refine but working
> Timeline in homepage still to refine but working

- src/config/serviceurl.js
> Predeploy service

- src/config/serviceurl.js
> Predepeploy

- package.json
> Added lib to package.json

- daf_data-portal.yml
- src/components/IngestionWizard/WizardFormMetadata.js
- src/config/serviceurl.js
- src/data/themes.js
- src/helpers/TrasformFormToDcat.js
> Deploy ingestion

- src/actions.js
- src/components/IngestionWizard/WizardFormMetadata.js
- src/config/serviceurl.js
> Deploy kube 1.9

- Dockerfile
> used yarn to fetch packages

- src/views/IngestionWizard/IngestionWizard.js
> Fix bug sftp path

- src/components/IngestionWizard/WizardFormMetadata.js
Changed text in form ingestion first page
> Changed text in form ingestion first page

- src/components/IngestionWizard/WizardFormMetadata.js
- src/views/DatasetDetail/DatasetDetail.js
Updated jupyter use in datasetdetails
> Updated jupyter use in datasetdetails

- src/components/IngestionWizard/WizardFormMetadata.js
- src/views/DatasetDetail/DatasetDetail.js
> Minor improvement in info 

- package-lock.json
- src/helpers/TrasformFormToDcat.js
Working ingestion form with new metadata complete kylo integration still to finish but working
> Working ingestion form with new metadata complete kylo integration still to finish but working

- src/views/DatasetDetail/DatasetDetail.js
> Minor still to test

- src/components/Sidebar/Sidebar.js
- src/views/UserStory/components/UserStoryEditor.jsx
- src/views/UserStory/components/UserStoryEditorContainer.jsx
- src/views/UserStory/components/bar/EditBarTop.jsx
- src/views/UserStory/components/widgets/BtnControlWidget.js
Fixed story issue on adding two consecutive text widgets only authors or daf_admins can now delete a userstory
> Fixed #264 

- package-lock.json
- package.json
- public/css/custom.css
- public/css/style.css
- src/actions.js
- src/components/Header/Header.js
- src/components/Header/Public/Header.js
- src/components/IngestionWizard/WizardForm.js
- src/containers/Full/Full.js
- src/containers/Public/Public.js
- src/routes.js
- src/views/DatasetDetail/DatasetDetail.js
- src/views/UserStory/components/SectionTitle.js
- src/views/UserStory/components/UserStoryEditor.jsx
- src/views/UserStory/components/UserStoryEditorContainer.jsx
- src/views/UserStory/components/UserStoryView.jsx
- src/views/UserStory/components/bar/EditBarTop.jsx
- src/views/UserStory/components/bar/ViewBar.jsx
- src/views/Widgets/service/WidgetService.js
- Added private/public information on dataset and userstories, minor fixes on header dropdowns, minor fixes and clean on dependencies
- Added steps on dataset ingestion
- Fixed hdfs/storage manager url
> General fixes and added minor informations

- src/views/UserStory/components/CustomFrame.jsx
- src/views/UserStory/components/UserStoryView.jsx
- src/views/UserStory/components/bar/EditBarTop.jsx
- src/views/UserStory/components/widgets/BtnControlWidget.js
Fixed check on moving up or down widgets in story
> BugFix for userstory move up/down widget

- Dockerfile/test/Dockerfile
- src/components/Aside/Aside.js
- src/components/IngestionWizard/WizardFormMetadata.js
- src/semantics/config/apiURLs.js
- src/sw.js
- src/views/DatasetDetail/DatasetDetail.js
- src/views/IngestionWizard/IngestionWizard.js
- src/views/Login/Login.js
Minor fixes on labels and notifications added notification for error
Merge branch 'master' of https://github.com/italia/daf-dataportal
Fixed semantics url
> Minor fixes on labels and notifications added notification for error

- src/actions.js
- src/components/Aside/Aside.js
- src/sw.js
- src/views/Notifications/Notifications.js
- src/views/Profile/Profile.js
- webpack/webpack.dev.js
- Web-push subscription management from user profile page
- New notification type for generic purpose
- Merge branch 'newSecurity' of https://github.com/italia/daf-dataportal into newSecurity
> New security

- package-lock.json
- package.json
- src/actions.js
- src/views/DashboardManager/components/DashboardEditor.jsx
- src/views/DashboardManager/components/DashboardView.jsx
- src/views/DashboardManager/components/services/WidgetService.js
- src/views/DataseList/DatasetList.js
- src/views/DatasetDetail/DatasetDetail.js
- src/views/UserStory/components/UserStoryEditorContainer.jsx
- src/views/Widgets/Widgets.js
- webpack/webpack.dev.js
Added call to open-iframes on story/dashboard creation
Fixed call on open-iframes for dataset detail
Preview dataset limited to 10 elements
Dataset Preview section updated with row limit and tabular preview for csv files
> Fixes and minor improvements

- src/helpers/TrasformFormToDcat.js
- src/views/Home/services/HomeService.js
iframes on private home call to open
SFTP Path modified on dataset ingestion
> Minor fixes

- package-lock.json
- package.json
- src/views/DatasetDetail/DatasetAdmin.js
- src/views/DatasetDetail/DatasetDetail.js
- src/views/Login/Login.js
- src/views/Register/Register.js
Minor fixes; redesigned registration page added recaptcha
Login redirect fix
> Registration and login fixes

- src/actions.js
- src/reducers.js
- src/views/DatasetDetail/DatasetAdmin.js
- src/views/DatasetDetail/DatasetDetail.js
- src/views/Register/Register.js
- src/views/Widgets/CreateWidget.js
Fixed Dataset detail on public page behaviour with resource download and preview
Bug fix orgs for Superset table
Publish on Ckan adds resources and daf information
> DATPOR-398 - Open data public detail

- src/actions.js
- src/reducers.js
- src/views/DatasetDetail/DatasetAdmin.js
- src/views/DatasetDetail/DatasetDetail.js
- src/views/Register/Register.js
- src/views/Widgets/CreateWidget.js
> New security - Merge from master

- package-lock.json
- src/actions.js
- src/containers/Full/Full.js
- src/reducers.js
- src/views/DatasetDetail/DatasetAdmin.js
- src/views/Login/Login.js
- src/views/Widgets/CreateWidget.js
- src/views/Widgets/QueryBuild.js
Minor fixes to Dataset admin page, and moved superset open cookie to login page
Improved Query builder
Query build working with new query reducer
Added Join functionality to query builder
Minor fixes on query builder: edit labels
> Query Builder and minor improvements

- package-lock.json
- package.json
- src/actions.js
- src/components/Widgets/Chart.js
- src/components/Widgets/QueryBuild.js
- src/containers/Full/Full.js
- src/routes.js
- src/utility.js
- src/views/DatasetDetail/DatasetAdmin.js
- src/views/DatasetDetail/DatasetDetail.js
- src/views/Widgets/CreateWidget.js
Fixed issue on modal for widget/query builder: no opendata org found
>  Fixed issue on modal for widget/query builder: no opendata org found and minor fixes

- src/components/IngestionWizardForm/WizardFormSecondPage.js
- src/components/IngestionWizardForm/renderField.js
DATPOR-490 Fixed minor bugs on form
> DATPOR-490 Fixed minor bugs on form

- test/Selenium_test_NoDAF_Admin.side
> add selenium test
